// <auto-generated />
using A1_123123123.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace A1_123123123.Migrations
{
    [DbContext(typeof(A1_123123123Context))]
    [Migration("20191106214100_Seed Data")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("A1_123123123.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animal");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Description = "Moos a lot",
                            Name = "Cow"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Waffles",
                            Name = "Donkey"
                        });
                });

            modelBuilder.Entity("A1_123123123.Models.PetFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NutritionalInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("PetFood");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            AnimalId = 2,
                            Brand = "PetSmart",
                            Description = "The cheapest of cheap",
                            Name = "Cheapfood",
                            NutritionalInfo = "ha!",
                            Price = 12.99m,
                            Weight = 20f
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 1,
                            Brand = "PetSmart",
                            Description = "The cheapest of cheap",
                            Name = "Cheapfood",
                            NutritionalInfo = "ha!",
                            Price = 12.99m,
                            Weight = 20f
                        });
                });

            modelBuilder.Entity("A1_123123123.Models.PetFood", b =>
                {
                    b.HasOne("A1_123123123.Models.Animal", "Animal")
                        .WithMany("PetFoods")
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
